"""empty message

Revision ID: ae71f7df9163
Revises: b4cc7214273e
Create Date: 2018-05-31 13:40:34.234527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae71f7df9163'
down_revision = 'b4cc7214273e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('service', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'service')
    # ### end Alembic commands ###
